services:
  db:
    image: postgres:18-alpine
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    environment:
      - POSTGRES_DB_NAME=ucar
      - POSTGRES_DB_USER=ucar
      - POSTGRES_DB_PASSWORD=ucar
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    command: >
      -c 'log_statement=all'
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db: